### ISSUE TITLE
Issues using gocd-gradle-plugin on Windows OS

### ISSUE THREAD

**Issue by twbutler** [jmnarloch/gocd-gradle-plugin#1]
I have discovered a couple of issues with the gradle plugin when running on Windows Server 2008. Here is my Task configuration - note that I want to use the gradle wrapper:

Task Type   Run If Conditions  
    Gradle  Passed  

Properties  
    Offline: false
    UseWrapper: true
    Tasks: clean build
    Debug: true
    AdditionalOptions:
    Deamon:
    GradleHome:

On Cancel
    No 

I have source code in a local/private Git repo that GoCD is cloning into the following folder: 
C:\Program Files (x86)\Go Agent\pipelines\TestOne

This folder contains (among other things) the generated gradlew and gradlew.bat files. When I try to trigger a build, it fails with this error: 

:
13:31:52.344 [go] Start to build TestOne/1/build/1/pref3_BuildAndUnitTest_review on fbi05 [C:\Program Files (x86)\Go Agent]
13:31:52.344 [go] Current job status: passed.

13:31:52.344 [go] Start to execute task: Plugin with ID: gradle.task.plugin.
13:31:52.453 **_Cannot run program "./gradlew" (in directory "pipelines\TestOne"): CreateProcess error=2, The system cannot find the file specified**_
13:31:52.453 java.io.IOException: Cannot run program "./gradlew" (in directory "pipelines\TestOne"): CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:113)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:62)
    at io.jmnarloch.cd.go.plugin.api.command.TaskCommand.execute(TaskCommand.java:64)
    at io.jmnarloch.cd.go.plugin.api.dispatcher.ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl.dispatch(ApiRequestDispatcherBuilder.java:176)
    at io.jmnarloch.cd.go.plugin.api.task.AbstractDispatchingTask.handle(AbstractDispatchingTask.java:107)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
    at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExecutor.execute(JsonBasedTaskExecutor.java:45)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.executeTask(PluggableTaskBuilder.java:97)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:74)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:71)
    at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExtension.execute(JsonBasedTaskExtension.java:56)
    at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.execute(TaskExtension.java:82)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.build(PluggableTaskBuilder.java:71)
    at com.thoughtworks.go.domain.builder.Builder.build(Builder.java:51)
    at com.thoughtworks.go.remote.work.Builders.build(Builders.java:63)
    at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:208)
    at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:183)
    at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:145)
    at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
    at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
    at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
    at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
    at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
    at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
    at java.lang.ProcessImpl.start(ProcessImpl.java:136)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 35 more

I think there are two issues. 

The first is that the plugin does not properly detect that it is running on Windows, and always tries to use the Unix gradlew command ("./gradlew", defined as GRADLEW_UNIX in the source).  Once this issue is corrected, then the plugin will correctly use "./gradlew.bat" (GRADLEW_WINDOWS),  In looking through the plugin source, I do not see an obvious problem with the logic that determines whether the application is running on Windows or not.  

```
private boolean isWindows() {
    final String os = environment.get("os.name");
    return !StringUtils.isBlank(os) && os.toLowerCase().contains("win");
}
```

However, a lot depends on the contents of "environment" above - this map appears to be passed in to the plugin by the Go Agent. I have not have time to connect a debugger to the Agent, but it would be interesting to know what is in there. 

The second issue is that the Windows command shell cannot determine/find the gradlew command to execute it ("CreateProcess error=2, The system cannot find the file specified").  I think if the full absolute path to the file is specified, then it will work.  In my case, the command string that the plugin should provide to the ProcessBuilder would be: 
C:/Program Files (x86)/Go Agent/pipelines/TestOne/gradlew.bat

Thanks for taking a look at this... please let me know if you need more information.

Trevor

**Comment by jmnarloch** [comment]
Hi Trevor,

Thank you for detailed description for reproducing the issue. I did had time to take a look at the code yesterday and I've done some refactoring together with addressing both of this issues. 

The OS check, has now fallback to System property and I'm specifying the absolute path to the wrapper script, though that wasn't needed for Unix like systems.

Would you find one extra minute to verify that this going to work as you expect? There is a (fail fast) path to verify that the gradle task executor works, by pulling the latest master version and running on the project:

```
./gradlew.bat clean build # this is going to run the simple test case that I've prepared
```

The longer path, would require you to download the [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/jmnarloch/gocd-gradle-plugin/1.0.1-SNAPSHOT/gocd-gradle-plugin-1.0.1-20151029.215323-4.jar) build from [OSS repo](https://oss.sonatype.org/content/repositories/snapshots/io/jmnarloch/gocd-gradle-plugin/1.0.1-SNAPSHOT/) install it directly in GO server and execute your pipeline.

If you could confirm that this works, I can do a release 1.0.1 with this fix.

**Comment by twbutler** [comment]
Jakub,

Thank you for working on this so quickly.  I will take time to fetch and try your latest code changes.  I should be able to do this sometime today, after I take care of my primary job duties…  You should hear back from me shortly…

Thanks,
Trevor

**Comment by twbutler** [comment]
I updated my checkout with the latest from SVN, and ran the build and tests.  I am seeing a test failure in shouldBuildGradleProject:

java.lang.AssertionError
       at org.junit.Assert.fail(Assert.java:86)
       at org.junit.Assert.assertTrue(Assert.java:41)
       at org.junit.Assert.assertTrue(Assert.java:52)
       at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutorTest.shouldBuildGradleProject(GradleTaskExecutorTest.java:76)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
       at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
       at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
       at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
       at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
       at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
       at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
       at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
       at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
       at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
       at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
       at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
       at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
       at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
       at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
       at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
       at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
       at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
       at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
       at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
       at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
       at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
       at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)

Standard output

Executing command: [C:\EclipseWorkspace4.2\gocd-gradle-plugin\src\test\resources\gradle.\gradlew.bat, clean, build]
Executing command: [C:\Users\trbutl.gradle\wrapper\dists\gradle-2.8-bin\4rsda7i357a5ogdj89yq8dntm\gradle-2.8\bin\gradle, clean, build]

Standard error

Could not find pluginId for logger: class io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor
Build failed with error

From: Trevor Butler Trevor.Butler-at-sas.com |GitHub/github| [mailto:l2poi3nt1t@sneakemail.com]
Sent: Friday, October 30, 2015 9:52 AM
To: Trevor Butler Trevor.Butler@sas.com; jmnarloch/gocd-gradle-plugin reply+00eac7fa69299c5ac4cb12b8092e7d45b9f7642279a6535092cf00000001124a580a92a169ce06cdc633-at-reply.github.com |GitHub/github| oazynoptrt@sneakemail.com; jmnarloch/gocd-gradle-plugin gocd-gradle-plugin@noreply.github.com
Cc: twbutler 783hegcx7g@snkmail.com
Subject: RE: [gocd-gradle-plugin] Issues using gocd-gradle-plugin on Windows OS (#1)

Jakub,

Thank you for working on this so quickly.  I will take time to fetch and try your latest code changes.  I should be able to do this sometime today, after I take care of my primary job duties…  You should hear back from me shortly…

Thanks,
Trevor

**Comment by jmnarloch** [comment]
Hmmm,

I might be wrong here, but my first guest is that the `./` in `/./gradlew.bat` brakes the path on Windows, I've commit the quick fix, but this time I will setup a windows machines and see if this is going to work.

Still I would wish that the CI would have possibility to run builds on Windows.

**Comment by twbutler** [comment]
Jakub,

I tried the latest change and the shouldBuildGradleProject test still fails in the same way.

I am going to grab the jar and try it in my GoCD server next…

Trevor

**Comment by jmnarloch** [comment]
The path:C:\Users\trbutl.gradle\wrapper\dists\gradle-2.8-bin\4rsda7i357a5ogdj89yq8dntm\gradle-2.8\bin\gradle points to gradle.**exe** doesn't it?

Actually it was .bat script that is used for execution.

**Comment by jmnarloch** [comment]
Hey,

I've done the final fixes and tests and I can confirm that the gradle plugin will also work on Windows. You can download the release from the [release page](https://github.com/jmnarloch/gocd-gradle-plugin/releases)

Happy using.

**Comment by twbutler** [comment]
Jakub,

Wow – thank you for so quickly fixing this.  You did not have to work over the weekend!  I will get your latest release and try it today.

Thanks,
Trevor

**Comment by twbutler** [comment]
Just got through using the new Gradle plugin version 1.0.1.  Everything looks good on my system.  My builds on Windows are now working as expected.

Thank you,
Trevor

From: Trevor Butler Trevor.Butler-at-sas.com |GitHub/github| [mailto:l2poi3nt1t@sneakemail.com]
Sent: Monday, November 02, 2015 10:20 AM
To: Trevor Butler Trevor.Butler@sas.com; jmnarloch/gocd-gradle-plugin reply+00eac7fa9fe89e255dc4e6eb90661c7c91ac9c2822c4ad6d92cf00000001124ccf7a92a169ce06cdc633-at-reply.github.com |GitHub/github| icloighqwt@sneakemail.com; jmnarloch/gocd-gradle-plugin gocd-gradle-plugin@noreply.github.com
Cc: twbutler 783hegcx7g@snkmail.com
Subject: RE: [gocd-gradle-plugin] Issues using gocd-gradle-plugin on Windows OS (#1)

Jakub,

Wow – thank you for so quickly fixing this.  You did not have to work over the weekend!  I will get your latest release and try it today.

Thanks,
Trevor
