### ISSUE TITLE
Issue when Go Server is Windows but Agent is Linux

### ISSUE THREAD

**Issue by twbutler** [jmnarloch/gocd-gradle-plugin#2]
Jakub,

Thanks for the work to support Windows.  I have been using version 1.0.1 of the gocd-gradle-plugin since you released it, and I am now seeing an issue. My Go Server is on a Windows host, but I now have an Agent on a new Linux VM. I also have a couple of Windows Agents.  Everything works fine when jobs run on the Windows Agents, but if a job runs on Linux, I see the following error (NOTE the backslash '\' character in the path to gradlew): 

:
15:54:58.021 [go] Start to execute task: Plugin with ID: gradle.task.plugin.
15:54:58.032 Cannot run program **"/var/lib/go-agent/pipelines\preferences-service/gradlew"** (in directory "pipelines\preferences-service"): error=2, No such file or directory
15:54:58.032 java.io.IOException: Cannot run program "/var/lib/go-agent/pipelines\preferences-service/gradlew" (in directory "pipelines\preferences-service"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:113)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:62)
    at io.jmnarloch.cd.go.plugin.api.command.TaskCommand.execute(TaskCommand.java:64)
    at io.jmnarloch.cd.go.plugin.api.dispatcher.ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl.dispatch(ApiRequestDispatcherBuilder.java:176)
    at io.jmnarloch.cd.go.plugin.api.task.AbstractDispatchingTask.handle(AbstractDispatchingTask.java:107)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
    at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExecutor.execute(JsonBasedTaskExecutor.java:45)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.executeTask(PluggableTaskBuilder.java:97)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:74)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:71)
    at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExtension.execute(JsonBasedTaskExtension.java:56)
    at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.execute(TaskExtension.java:82)
    at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.build(PluggableTaskBuilder.java:71)
    at com.thoughtworks.go.domain.builder.Builder.build(Builder.java:51)
    at com.thoughtworks.go.remote.work.Builders.build(Builders.java:63)
    at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:208)
    at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:183)
    at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:145)
    at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
    at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
    at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
    at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
    at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
    at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 35 more

Thanks,
Trevor

**Comment by jmnarloch** [comment]
OK, so I am not sure where did this '\' come from. Generally in Java under Windows all paths in form /dir/file are acceptable and automatically translated into the correct Windows paths, at least the relative ones. I will have to investigate this.

**Comment by twbutler** [comment]
Thank you…  hopefully it will turn out to be a quick fix…

**Comment by twbutler** [comment]
Jakub,

Thanks for your efforts! 

I have now tried version 1.0.3...  Things look better, but still there is a problem with a path. The absolute path has been fixed - it now has all forward slashes.  However, the relative path (in **bold** below) still has the backslash character '\'.  

21:05:21.472 [go] Start to execute task: Plugin with ID: gradle.task.plugin.
21:05:21.541 Cannot run program "/var/lib/go-agent/pipelines/audit-service/gradlew" (**in directory "pipelines\audit-service"**): error=2, No such file or directory
21:05:21.542 java.io.IOException: Cannot run program "/var/lib/go-agent/pipelines/audit-service/gradlew" (in directory "pipelines\audit-service"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:113)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:62)
    at io.jmnarloch.cd.go.plugin.api.command.TaskCommand.execute(TaskCommand.java:64)
    at io.jmnarloch.cd.go.plugin.api.dispatcher.ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl.dispatch(ApiRequestDispatcherBuilder.java:176)
    at io.jmnarloch.cd.go.plugin.api.task.AbstractDispatchingTask.handle(AbstractDispatchingTask.java:107)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)

**Comment by jmnarloch** [comment]
Final fix (I hope). Previously I have change only the gradle script path to fix this, forgetting about setting the working directory. This should be now resolved: https://github.com/jmnarloch/gocd-gradle-plugin/releases/tag/1.0.4

Still clearly this is bug in Go CD itself.

**Comment by twbutler** [comment]
Jakub,

Thanks again for working on this and producing a working solution!  I just tried 1.0.4 and was able to get pipelines to run successfully on both Win and Linux.

Regards,
Trevor

**Comment by jmnarloch** [comment]
Cool, I am closing this issue then.
