### ISSUE TITLE
gocd version 16.3.0 run gradle-plugin issue

### ISSUE THREAD

**Issue by ytc301** [jmnarloch/gocd-gradle-plugin#7]
plugin-gradle.task.plugin.log

2016-04-21 13:36:48,867  INFO [Thread-70] GradleTask:52 - Dispatching request: configuration
2016-04-21 13:36:48,867  INFO [Thread-70] ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl:52 - Executing command for request: configuration
2016-04-21 13:36:48,892  INFO [Thread-70] GradleTask:52 - Dispatching request: view
2016-04-21 13:36:48,892  INFO [Thread-70] ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl:52 - Executing command for request: view
2016-04-21 13:36:48,908  INFO [Thread-70] GradleTask:52 - Dispatching request: go.plugin-settings.get-configuration
2016-04-21 13:36:48,908  INFO [Thread-70] ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl:52 - No command found for request: go.plugin-settings.get-configuration
2016-04-21 13:36:48,908 ERROR [Thread-70] GradleTask:77 - Unexpected error occurred when processing request.
com.thoughtworks.go.plugin.api.exceptions.UnhandledRequestTypeException: This is an invalid request type :go.plugin-settings.get-configuration
    at io.jmnarloch.cd.go.plugin.api.dispatcher.ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl.dispatch(ApiRequestDispatcherBuilder.java:172)
    at io.jmnarloch.cd.go.plugin.api.task.AbstractDispatchingTask.handle(AbstractDispatchingTask.java:107)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
    at com.thoughtworks.go.plugin.access.common.settings.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:45)
    at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.getPluginSettingsConfiguration(TaskExtension.java:69)
    at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:63)
    at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:47)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:262)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:353)
    at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:111)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:97)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:152)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:109)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:288)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:319)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:286)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:210)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:198)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:184)

**Comment by ytc301** [comment]
go-server.log error log

2016-04-21 13:36:48,916 ERROR [Thread-70] PluginSettingsMetadataLoader:72 - Failed to fetch Plugin Settings metadata for plugin : gradle.task.plugin
java.lang.RuntimeException: Interaction with plugin with id 'gradle.task.plugin' implementing 'task' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":"This is an invalid request type :go.plugin-settings.get-configuration"}']
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:38)
    at com.thoughtworks.go.plugin.access.common.settings.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:45)
    at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.getPluginSettingsConfiguration(TaskExtension.java:69)
    at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:63)
    at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:47)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:262)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:353)
    at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:111)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:97)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:152)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:109)
    at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:288)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:319)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:286)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:210)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:198)
    at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:184)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":"This is an invalid request type :go.plugin-settings.get-configuration"}'
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:36)
    ... 18 more
2016-04-21 13:36:49,022  INFO [main] ConsoleActivityMonitor:67 - Found '0' building jobs. Added them with '2016-04-21T13:36:48.912+08:00' as the last heard time
2016-04-21 13:36:49,127  INFO [main] RailsAssetsService:66 - Found rails assets manifest file named .sprockets-manifest-d33fb0a863b2d176be4dc03338085ff1.json 
2016-04-21 13:36:49,161  INFO [main] RailsAssetsService:70 - Successfully read rails assets manifest file located at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/public/assets/.sprockets-manifest-d33fb0a863b2d176be4dc03338085ff1.json
2016-04-21 13:37:13,918  WARN [qtp1334729950-16] FeatureToggleRepository:68 - Toggles file, /etc/go/go.feature.toggles does not exist. Saying there are no toggles.

**Comment by alejoz93** [comment]
yo estoy teniendo el mismo problema!

**Comment by alejoz93** [comment]
Yo estoy teniendo el mismo problema...

**Comment by alejoz93** [comment]
I'm having the same problem ...
